version: '2'
services:
  api:
    image: openeats/api
    command: ./base/gunicorn_start.sh
    restart: always
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      env_prod.list
  node:
    image: openeats/node
    command: npm start
    volumes:
      - node_modules:/code/node_modules
    depends_on:
      - api
    ports:
      - "8080:8080"
    env_file:
      env_prod.list
  db:
    image: mariadb
    env_file:
      env_prod.list
  nginx:
    image: openeats/nginx
    ports:
      - "80:80"
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
    depends_on:
      - api
      - node
    env_file:
      env_prod.list
    #TODO: For whatever reason the env vars are not being read correctly. They need to be manually replaace below.
    # Sed replace the API_PORT and NODE_PORT vars so nginx can serve them.
    command: /bin/bash -c "sed -i 's/API_PORT/8000/g' /etc/nginx/conf.d/default.conf && sed -i 's/NODE_PORT/8080/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
volumes:
  database:
  node_modules:
  static-files:
  site-media: