version: '2'
services:
  api:
    command: ./base/gunicorn_start.sh
    env_file:
      env_stg.list
  node:
    command: npm start
    env_file:
      env_stg.list
  db:
    env_file:
      env_stg.list
  nginx:
    build: services/
    ports:
      - "80:80"
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
    depends_on:
      - api
      - node
    env_file:
      env_stg.list
    command: /bin/bash -c "sed -i 's/API_PORT/8000/g' /etc/nginx/conf.d/default.conf && sed -i 's/NODE_PORT/8080/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
